### ISSUE TITLE
Failed to resolve async component:

### ISSUE THREAD

**Issue by xtt55** [WeBankFinTech/Scriptis#29]
[Vue warn]: Failed to resolve async component: function component() {
    return Promise.all(/*! import() */[__webpack_require__.e(1), __webpack_require__.e(0), __webpack_require__.e(10)]).then(__webpack_require__.bind(null, /*! ./container.vue */ "./src/js/module/workbench/container.vue"));
  }
Reason: TypeError: Cannot read property 'Vue' of undefined

**Comment by LuShengbai** [comment]
I also had the same problem!
