### ISSUE TITLE
How to set Error  tips Messagebox staying long

### ISSUE THREAD

**Issue by dawsongzhao** [WeBankFinTech/Scriptis#32]
while there is some error message . the messagebox flashes so fast that it is hard to read the message info.

**Comment by wushengyeyouya** [comment]
Thanks very much! We will optimize it in next version.

**Comment by demonray** [comment]
@dawsongzhao like this,  set `duration` you wanted
`
Vue.prototype.$Message.config({
  duration: 3
})
`
For global use, append it to file `src/main.js`.
